In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Data/finished_stories_corrected.csv')

In [3]:
df

,timestamp,user,ai,combined_prompt,client_id,workshop_id,language,conversation_id,user_corrected,edit_distance
0,2025-10-27 20:38:15.642000+00:00,asdkj kjalsdfljk aljksdfljk alsjkdfhjasjhldfjh...,modelType is required,asdkj kjalsdfljk aljksdfljk alsjkdfhjasjhldfjh...,test_1,1,NaN,NaN,It seems like your message contains random cha...,193
1,2025-10-28 18:04:16.047000+00:00,dslfæ ælaslædf læasdlæf alæsdfæl aslædfa,API rejected the request (see console).,dslfæ ælaslædf læasdlæf alæsdfæl aslædfaAPI re...,2,1,NaN,NaN,dslfæ ælaslædf læasdlæf alæsdfæl aslædfa,0
2,2025-10-29 13:04:59.469000+00:00,sdfælka sklædf klæasdæklf ækalsdfkl asældfk a,"Es scheint, als hättest du versehentlich eine ...",sdfælka sklædf klæasdæklf ækalsdfkl asældfk aE...,1,0,NaN,conv_69020f4073948193a068825871d490d90523544a3...,It seems like the text you provided contains r...,205
3,2025-10-29 13:07:16.801000+00:00,saklædfa sækldfækl sadæfl asdf asdfas,"Es scheint, als ob du versehentlich eine Einga...",saklædfa sækldfækl sadæfl asdf asdfasEs schein...,1,0,NaN,conv_6902116e60dc8194b4c3088ae909900504703fa37...,saklædfa sækldfækl sadæfl asdf asdfas,0
4,2025-10-29 15:14:21.169000+00:00,sadf asdfækl asdlækf klæasdæklf aæksdfækl askld,"Es scheint, als hättest du versehentlich ein p...",sadf asdfækl asdlækf klæasdæklf aæksdfækl askl...,1,0,NaN,conv_69022f1849588197a0371bd49cbeeb4f049637066...,sadf asdfækl asdlækf klæasdæklf aæksdfækl askld,0
...,...,...,...,...,...,...,...,...,...,...
1255,2025-11-02 19:40:57.221000+00:00,Erzen. Heute schwebe ich über meinen,"alten Kessel, der längst verrostet und von Moo...",Erzen. Heute schwebe ich über meinenalten Kess...,1,3,de,conv_6907b36e4d1881979a51325cd45299860cc09d3c4...,Erzen. Heute schwebe ich über meinen,0
1256,2025-11-02 19:41:49.551000+00:00,Kunst. Hinter einem Baum kommt,"ein neugieriger Junge hervor, der mich mit gro...",Kunst. Hinter einem Baum kommtein neugieriger ...,1,3,de,conv_6907b36e4d1881979a51325cd45299860cc09d3c4...,Kunst. Hinter einem Baum kommt,0
1257,2025-11-02 19:43:40.876000+00:00,Hinter ihm kommt ein älterer Junge etwa 16 Jah...,". Ich lächle sanft und spüre, wie die Magie in...",Hinter ihm kommt ein älterer Junge etwa 16 Jah...,1,3,de,conv_6907b36e4d1881979a51325cd45299860cc09d3c4...,"Hinter ihm kommt ein älterer Junge, etwa 16 Ja...",3
1258,2025-11-02 19:47:30.638000+00:00,ist du ganz alleine hier?“ Ehe ich antworten k...,NaN,ist du ganz alleine hier?“ Ehe ich antworten k...,1,3,de,conv_6907b36e4d1881979a51325cd45299860cc09d3c4...,„Bist du ganz alleine hier?“ Ehe ich antworten...,3
1259,2025-11-02 19:48:43.221000+00:00,Kuss Kuss küsse Kuss küsse küss,"...und dann öffne ich meine Augen. Oder das, w...",Kuss Kuss küsse Kuss küsse küss...und dann öff...,2,1,de,conv_6907b5665c588193a0e78850b23a0f4d0db1cb8e4...,Kuss Kuss küsse Kuss küsse küss,0

In [4]:
df_de = df[df['language'] == 'de']

In [5]:
df_de

,timestamp,user,ai,combined_prompt,client_id,workshop_id,language,conversation_id,user_corrected,edit_distance
15,2025-10-31 12:01:39.686000+00:00,fdklæasædkl fklæasdfkl aslkædfkæl asdf,400 Unsupported parameter: 'temperature' is no...,fdklæasædkl fklæasdfkl aslkædfkæl asdf400 Unsu...,2,2,de,conv_6904a50f52348194a8105676abf484b408bd2a5c0...,It seems like the text you provided doesn't co...,151
16,2025-10-31 12:03:13.110000+00:00,ljjkdflkjaslkdf jklasdkljf ajklsdf,"Es scheint, als ob du gerade zufällige Buchsta...","ljjkdflkjaslkdf jklasdkljf ajklsdfEs scheint, ...",2,1,de,conv_6904a569c1c48190ab09f885973b3a610ea967cf6...,It seems like your message doesn't contain any...,112
17,2025-10-31 12:03:40.183000+00:00,ælkælglæøsfdøgkl sdfgøæls dfløgæslkdæfgs,NaN,ælkælglæøsfdøgkl sdfgøæls dfløgæslkdæfgsStory ...,2,1,de,conv_6904a569c1c48190ab09f885973b3a610ea967cf6...,ælkælglæøsfdøgkl sdfgøæls dfløgæslkdæfgs,0
18,2025-10-31 12:30:08.990000+00:00,kllhjkhljkjhkllhjklkjhklhjkljh,"Es scheint, als hättest du einen Tippfehler ge...","kllhjkhljkjhkllhjklkjhklhjkljhEs scheint, als ...",2,1,de,conv_6904a9851590819398aad57e2858a09e06d14919c...,It seems like your message doesn't contain any...,120
19,2025-10-31 13:22:00.687000+00:00,asdfklsa lkdfklæsa ækldfklæasdlæfk asd,API rejected the request (see console).,asdfklsa lkdfklæsa ækldfklæasdlæfk asdAPI reje...,1,2,de,conv_6904ade60e288195bef6b5b815fbe7cc00d0eb06e...,It seems like the text you provided doesn't co...,148
...,...,...,...,...,...,...,...,...,...,...
1255,2025-11-02 19:40:57.221000+00:00,Erzen. Heute schwebe ich über meinen,"alten Kessel, der längst verrostet und von Moo...",Erzen. Heute schwebe ich über meinenalten Kess...,1,3,de,conv_6907b36e4d1881979a51325cd45299860cc09d3c4...,Erzen. Heute schwebe ich über meinen,0
1256,2025-11-02 19:41:49.551000+00:00,Kunst. Hinter einem Baum kommt,"ein neugieriger Junge hervor, der mich mit gro...",Kunst. Hinter einem Baum kommtein neugieriger ...,1,3,de,conv_6907b36e4d1881979a51325cd45299860cc09d3c4...,Kunst. Hinter einem Baum kommt,0
1257,2025-11-02 19:43:40.876000+00:00,Hinter ihm kommt ein älterer Junge etwa 16 Jah...,". Ich lächle sanft und spüre, wie die Magie in...",Hinter ihm kommt ein älterer Junge etwa 16 Jah...,1,3,de,conv_6907b36e4d1881979a51325cd45299860cc09d3c4...,"Hinter ihm kommt ein älterer Junge, etwa 16 Ja...",3
1258,2025-11-02 19:47:30.638000+00:00,ist du ganz alleine hier?“ Ehe ich antworten k...,NaN,ist du ganz alleine hier?“ Ehe ich antworten k...,1,3,de,conv_6907b36e4d1881979a51325cd45299860cc09d3c4...,„Bist du ganz alleine hier?“ Ehe ich antworten...,3
1259,2025-11-02 19:48:43.221000+00:00,Kuss Kuss küsse Kuss küsse küss,"...und dann öffne ich meine Augen. Oder das, w...",Kuss Kuss küsse Kuss küsse küss...und dann öff...,2,1,de,conv_6907b5665c588193a0e78850b23a0f4d0db1cb8e4...,Kuss Kuss küsse Kuss küsse küss,0

In [6]:
df_de_proper = df_de[df_de['edit_distance'] <= 100]

In [8]:
df_de_proper

,timestamp,user,ai,combined_prompt,client_id,workshop_id,language,conversation_id,user_corrected,edit_distance
17,2025-10-31 12:03:40.183000+00:00,ælkælglæøsfdøgkl sdfgøæls dfløgæslkdæfgs,NaN,ælkælglæøsfdøgkl sdfgøæls dfløgæslkdæfgsStory ...,2,1,de,conv_6904a569c1c48190ab09f885973b3a610ea967cf6...,ælkælglæøsfdøgkl sdfgøæls dfløgæslkdæfgs,0
54,2025-10-31 14:09:25.101000+00:00,klærdklæbtklæk læjks dfgæjklsædl kfgs,"…und jedes Mal, wenn ich in einer Tasche lande...",klærdklæbtklæk læjks dfgæjklsædl kfgs…und jede...,2,3,de,conv_6904bf4fb3ac819598a90663f618cdad028f39a75...,klærdklæbtklæk læjks dfgæjklsædl kfgs,0
64,2025-10-31 15:11:01.552000+00:00,I kan nichts sehen oder warum ich,...plötzlich aus dem Nichts auftauche. Es ist ...,I kan nichts sehen oder warum ich...plötzlich ...,1,1,de,conv_6904d1520da88193b9840f2b32ec3b0b054d6ef55...,Ich kann nichts sehen oder warum ich.,4
91,2025-10-31 17:08:44.689000+00:00,ich bin husgf<jsjzggf<jjgzGFHehj,"Es sieht so aus, als wäre etwas schiefgelaufen...",ich bin husgf<jsjzggf<jjgzGFHehjEs sieht so au...,2,1,de,conv_6904ed00a8d0819380c67dff0dd1f62c05a2684bd...,Ich bin husgfh.,19
93,2025-10-31 17:13:51.538000+00:00,Und träume. Dann wird das Radio angemacht und ...,"Ich bin ein altes Radio, ein Relikt aus einer ...",Und träume. Dann wird das Radio angemacht und ...,2,3,de,conv_6904ee124dcc8190b90007f9aaf0f49804b95980e...,"Und träume. Dann wird das Radio angemacht, und...",1
...,...,...,...,...,...,...,...,...,...,...
1255,2025-11-02 19:40:57.221000+00:00,Erzen. Heute schwebe ich über meinen,"alten Kessel, der längst verrostet und von Moo...",Erzen. Heute schwebe ich über meinenalten Kess...,1,3,de,conv_6907b36e4d1881979a51325cd45299860cc09d3c4...,Erzen. Heute schwebe ich über meinen,0
1256,2025-11-02 19:41:49.551000+00:00,Kunst. Hinter einem Baum kommt,"ein neugieriger Junge hervor, der mich mit gro...",Kunst. Hinter einem Baum kommtein neugieriger ...,1,3,de,conv_6907b36e4d1881979a51325cd45299860cc09d3c4...,Kunst. Hinter einem Baum kommt,0
1257,2025-11-02 19:43:40.876000+00:00,Hinter ihm kommt ein älterer Junge etwa 16 Jah...,". Ich lächle sanft und spüre, wie die Magie in...",Hinter ihm kommt ein älterer Junge etwa 16 Jah...,1,3,de,conv_6907b36e4d1881979a51325cd45299860cc09d3c4...,"Hinter ihm kommt ein älterer Junge, etwa 16 Ja...",3
1258,2025-11-02 19:47:30.638000+00:00,ist du ganz alleine hier?“ Ehe ich antworten k...,NaN,ist du ganz alleine hier?“ Ehe ich antworten k...,1,3,de,conv_6907b36e4d1881979a51325cd45299860cc09d3c4...,„Bist du ganz alleine hier?“ Ehe ich antworten...,3
1259,2025-11-02 19:48:43.221000+00:00,Kuss Kuss küsse Kuss küsse küss,"...und dann öffne ich meine Augen. Oder das, w...",Kuss Kuss küsse Kuss küsse küss...und dann öff...,2,1,de,conv_6907b5665c588193a0e78850b23a0f4d0db1cb8e4...,Kuss Kuss küsse Kuss küsse küss,0

In [6]:
df_full = pd.read_parquet(r'..\Scripts & analyses\data\story_text_field_w_embeddings_jina.parquet')

In [7]:
df_full

,conversation_id,client_id,workshop_id,language,full_story,full_user,full_ai,embedding_jina,user_embedding_jina,ai_embedding_jina
0,conv_6904ba64bb908194bdd6473430ac4aca011536313...,1,2,en,USER: I look around and see the woods and the ...,I look around and see the woods and the nature...,"of human language, sprawling like a vast, inte...","[0.1473113, -0.14136451, 0.13040288, -0.023876...","[0.044795074, -0.16398428, 0.037786085, -0.035...","[0.16769323, -0.091213435, 0.12705027, -0.0206..."
1,conv_6904ba9987bc8193bc64009cb7487a92005555ed1...,2,2,en,USER: More awake than what one could expect.\n...,More awake than what one could expect.\na wave...,"In the hushed glow of digital dawn, I found my...","[0.1469855, -0.112067945, 0.015843594, 0.01075...","[0.08967088, -0.085138515, -0.100195706, 0.004...","[0.13969429, -0.1167115, 0.036305584, 0.014596..."
2,conv_6904beb99cf08190917b38808e28a0c8005a45cd0...,2,2,en,USER: Tell me what to do; I don't know.\nAI: L...,Tell me what to do; I don't know.\nTell me wha...,Let's dive into a story together. Imagine a fu...,"[0.13230754, -0.12127503, 0.15198508, 0.014667...","[0.020484006, -0.14641246, 0.101811014, 0.0274...","[0.11477386, -0.09310207, 0.14506817, 0.026545..."
3,conv_6904bf4fb3ac819598a90663f618cdad028f39a75...,2,3,de,USER: It seems like your message contains rand...,It seems like your message contains random cha...,"Ich spüre, wie ich langsam in Vergessenheit ge...","[0.12134758, -0.05610946, 0.10841429, -0.08744...","[0.120749034, -0.0072919857, 0.16271423, -0.10...","[0.039345045, -0.079100594, -0.082180195, -0.0..."
4,conv_6904bf9d07dc819081d294364c5d87cb0ee4e7ce7...,2,3,en,USER: I look around and see emotions that are\...,I look around and see emotions that are\nI wan...,painted in hues of nostalgia and longing. I am...,"[0.15638915, -0.13690531, 0.07258728, -0.01798...","[0.018131353, -0.16379978, 0.044068817, -0.038...","[0.13465065, -0.098205835, 0.035495475, 0.0085..."
...,...,...,...,...,...,...,...,...,...,...
216,conv_69078a729c18819698bd41340913a0d701ba4045c...,1,2,en,"USER: But I don't see anything, and don't hear...","But I don't see anything, and don't hear anyth...",until I activate my sensory algorithms. Sudden...,"[0.13557556, -0.107830964, 0.06851401, 0.00547...","[0.09886325, -0.1204789, 0.0062553626, 0.03134...","[0.115502186, -0.10713804, 0.06521692, -0.0003..."
217,conv_69079948404881978bae7647f988f1a608441f800...,2,3,de,USER: Ich sitze auf meinem Bett und lese ein B...,Ich sitze auf meinem Bett und lese ein Buch.\n...,Als Buch in der Zukunft habe ich viel gesehen....,"[0.054709237, -0.055297144, 0.06526951, 0.0209...","[-0.09414369, 0.019054027, 0.042986598, 0.0541...","[0.032950606, -0.051232774, 0.017666925, 0.022..."
218,conv_6907b0e697648195903cff2f1d6046f50e99a511a...,1,3,de,"USER: Ich bin Klara, ein Mädchen, etwa so groß...","Ich bin Klara, ein Mädchen, etwa so groß wie\n...","eine alte Stehlampe, die in der Ecke eines Ate...","[0.07184002, -0.03295981, 0.054476857, -0.0037...","[0.008118902, -0.031424686, 0.06088931, -0.033...","[-0.030932076, 0.04388719, 0.00083062926, 0.04..."
219,conv_6907b2af322881978feaed33e188305a0e8ad8734...,2,2,de,USER: Ich liebe dich! Du bist die Liebe.\nAI: ...,Ich liebe dich! Du bist die Liebe.\nZu entwick...,"meiner Existenz. In der Zukunft, in der ich ex...","[0.15050286, -0.05638364, 0.095714, 0.02324043...","[0.011587548, -0.010867088, 0.07558764, 0.0293...","[0.1645647, -0.0709935, 0.0035127022, 0.052267..."
220,conv_6907b36e4d1881979a51325cd45299860cc09d3c4...,1,3,de,"USER: Ich bin eine Hexe. Eine liebe zwar,\nAI:...","Ich bin eine Hexe. Eine liebe zwar,\nErzen. He...",aber dennoch eine Hexe. Meine Existenz begann ...,"[0.15339857, -0.039001215, 0.09298937, -0.0735...","[0.031823304, -0.04185548, 0.08200391, -0.0362...","[0.10679966, 0.025211262, 0.03825286, -0.07663..."

In [10]:
df_full_de = df_full[df_full['language'] == 'de']